from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from typing import Any, cast

ROOT = Path(__file__).resolve().parents[1]


def _load_checker() -> Any:
    spec = importlib.util.spec_from_file_location(
        "clusterfuzzlite_requirements_checker",
        ROOT / "scripts" / "check_clusterfuzzlite_requirements.py",
    )
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    cast(Any, spec.loader).exec_module(module)
    return module


CHECKER = _load_checker()


def test_export_command_uses_frozen_runtime_lock(tmp_path: Path) -> None:
    output_path = tmp_path / "requirements.txt"

    assert CHECKER.export_command("uv", output_path) == [
        "uv",
        "export",
        "--frozen",
        "--no-dev",
        "--no-emit-project",
        "--format",
        "requirements.txt",
        "--output-file",
        str(output_path),
    ]


def test_header_normalization_ignores_temporary_output_path() -> None:
    committed = (
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv export --frozen --no-dev --no-emit-project --format requirements.txt "
        "--output-file .clusterfuzzlite/requirements.txt\n"
        "package==1.0 \\\n"
        "    --hash=sha256:abc\n"
    )
    exported = (
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv export --frozen --no-dev --no-emit-project --format requirements.txt "
        "--output-file C:/tmp/recon-cfl-export/requirements.txt\n"
        "package==1.0 \\\n"
        "    --hash=sha256:abc\n"
    )

    assert CHECKER.normalize_export(committed) == CHECKER.normalize_export(exported)


def test_audit_reports_stale_dependency_export() -> None:
    committed = (
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv export --frozen --no-dev --no-emit-project --format requirements.txt "
        "--output-file .clusterfuzzlite/requirements.txt\n"
        "package==1.0 \\\n"
        "    --hash=sha256:abc\n"
    )
    exported = (
        "# This file was autogenerated by uv via the following command:\n"
        "#    uv export --frozen --no-dev --no-emit-project --format requirements.txt "
        "--output-file C:/tmp/recon-cfl-export/requirements.txt\n"
        "package==1.1 \\\n"
        "    --hash=sha256:def\n"
    )

    audit = CHECKER.audit_requirements(committed, exported)

    assert not audit.ok
    assert any("-package==1.0 \\" in line for line in audit.diff)
    assert any("+package==1.1 \\" in line for line in audit.diff)


def test_audit_accepts_matching_current_export() -> None:
    text = (ROOT / ".clusterfuzzlite" / "requirements.txt").read_text(encoding="utf-8")

    audit = CHECKER.audit_requirements(text, text)

    assert audit.ok
    assert audit.committed_line_count > 100
