"""Shared constants for service names generated by DNS detection code.

These are NOT from fingerprints.yaml — they're hardcoded labels produced
by dns.py for M365 CNAME checks and email security records. Centralised
here so dns.py and insights.py stay in sync.

NOTE: SVC_DKIM_EXCHANGE is named for Exchange Online specifically because
the DKIM selectors we check (selector1/selector2._domainkey) are
Exchange-specific. Generic DKIM detection would need different selectors.
"""

# M365 CNAME-detected services
SVC_EXCHANGE_AUTODISCOVER = "Exchange Autodiscover"
SVC_MICROSOFT_TEAMS = "Microsoft Teams"
SVC_INTUNE_MDM = "Intune / MDM"
SVC_OFFICE_PROPLUS = "Office ProPlus (msoid)"
SVC_DKIM_EXCHANGE = "DKIM (Exchange Online)"

# Generic DKIM — detected via Google or other common selectors
SVC_DKIM = "DKIM"

# Email security labels
SVC_SPF_STRICT = "SPF: strict (-all)"
SVC_SPF_SOFTFAIL = "SPF: softfail (~all)"
SVC_DMARC = "DMARC"
SVC_BIMI = "BIMI"
SVC_MTA_STS = "MTA-STS"
