#!/usr/bin/env python3
"""Check that the ClusterFuzzLite runtime requirements export is current."""

from __future__ import annotations

import argparse
import difflib
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REQUIREMENTS_PATH = ROOT / ".clusterfuzzlite" / "requirements.txt"
EXPORT_ARGS = (
    "export",
    "--frozen",
    "--no-dev",
    "--no-emit-project",
    "--format",
    "requirements.txt",
)
CANONICAL_HEADER_COMMAND = (
    "#    uv export --frozen --no-dev --no-emit-project "
    "--format requirements.txt --output-file .clusterfuzzlite/requirements.txt"
)
AUTOGENERATED_HEADER_PREFIX = "#    uv export --frozen --no-dev --no-emit-project --format requirements.txt"


@dataclass(frozen=True)
class RequirementsAudit:
    committed_line_count: int
    exported_line_count: int
    diff: tuple[str, ...]

    @property
    def ok(self) -> bool:
        return not self.diff


def export_command(uv_bin: str, output_path: Path) -> list[str]:
    return [uv_bin, *EXPORT_ARGS, "--output-file", str(output_path)]


def normalize_export(text: str) -> str:
    lines = text.replace("\r\n", "\n").splitlines()
    if len(lines) >= 2 and lines[1].startswith(AUTOGENERATED_HEADER_PREFIX):
        lines[1] = CANONICAL_HEADER_COMMAND
    return "\n".join(lines) + "\n"


def audit_requirements(committed_text: str, exported_text: str) -> RequirementsAudit:
    committed = normalize_export(committed_text)
    exported = normalize_export(exported_text)
    diff: tuple[str, ...] = ()
    if committed != exported:
        diff = tuple(
            difflib.unified_diff(
                committed.splitlines(),
                exported.splitlines(),
                fromfile=".clusterfuzzlite/requirements.txt",
                tofile="uv export",
                lineterm="",
            )
        )
    return RequirementsAudit(
        committed_line_count=len(committed.splitlines()),
        exported_line_count=len(exported.splitlines()),
        diff=diff,
    )


def generate_requirements(uv_bin: str) -> str:
    with tempfile.TemporaryDirectory(prefix="recon-cfl-export-") as tmp:
        output_path = Path(tmp) / "requirements.txt"
        command = export_command(uv_bin, output_path)
        try:
            completed = subprocess.run(  # noqa: S603 - fixed dev-tool argv plus caller-selected executable.
                command,
                cwd=ROOT,
                text=True,
                capture_output=True,
                check=False,
            )
        except FileNotFoundError as exc:
            raise RuntimeError(f"{uv_bin!r} was not found on PATH") from exc
        if completed.returncode != 0:
            details = "\n".join(part for part in (completed.stdout.strip(), completed.stderr.strip()) if part)
            raise RuntimeError(f"uv export failed with exit code {completed.returncode}\n{details}")
        return output_path.read_text(encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Check that .clusterfuzzlite/requirements.txt matches the frozen runtime export."
    )
    parser.add_argument("--requirements", type=Path, default=REQUIREMENTS_PATH, help="Committed requirements file.")
    parser.add_argument("--uv", default="uv", help="uv executable to run.")
    args = parser.parse_args(argv)

    committed_text = args.requirements.read_text(encoding="utf-8")
    try:
        exported_text = generate_requirements(args.uv)
    except RuntimeError as exc:
        print(f"ClusterFuzzLite requirements check failed: {exc}", file=sys.stderr)
        return 1

    audit = audit_requirements(committed_text, exported_text)
    if not audit.ok:
        print("ClusterFuzzLite requirements export is stale.", file=sys.stderr)
        print("Regenerate it with:", file=sys.stderr)
        print(
            "  uv export --frozen --no-dev --no-emit-project --format requirements.txt "
            "--output-file .clusterfuzzlite/requirements.txt",
            file=sys.stderr,
        )
        print("", file=sys.stderr)
        print("\n".join(audit.diff), file=sys.stderr)
        return 1

    print(
        "OK: .clusterfuzzlite/requirements.txt matches the frozen uv runtime export "
        f"({audit.committed_line_count} lines)."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
